security:
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true

    encoders:
        Sulu\Bundle\SecurityBundle\Entity\User: bcrypt

    providers:
        sulu:
            id: sulu_security.user_provider

    access_control:
        - { path: "^%sulu_admin_prefix%/reset", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%/security/reset", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%/login$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%/_wdt", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%/translations", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%/$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^%sulu_admin_prefix%", roles: ROLE_USER }

    firewalls:
        admin:
            pattern: ^/
            anonymous: ~
            entry_point: sulu_security.authentication_entry_point
            json_login:
                check_path: sulu_admin.login_check
                success_handler: sulu_security.authentication_handler
                failure_handler: sulu_security.authentication_handler
            logout:
                path: sulu_admin.logout
                success_handler: sulu_security.logout_success_handler

sulu_security:
    checker:
        enabled: true
