_wdt:
    defaults:
        _requestAnalyzer: false
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   "%sulu_admin_prefix%/_wdt"

_profiler:
    defaults:
        _requestAnalyzer: false
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   "%sulu_admin_prefix%/_profiler"
